#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../../_env"

# Note: we cannot run "gitea" as root
kubectl exec deployment/gitea --container=gitea --namespace=gitea --quiet -- \
gitea --quiet $*
