#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../_env"
. "$ROOT/library/_trap"
. "$HERE/_env"

"$ROOT/platforms/kind/use" management

BLUEPRINT=$(porchctl rpkg init network-function --workspace=v1 --repository="$GIT_BLUEPRINTS_REPO" --namespace=porch-demo | cut --delimiter=' ' --fields=1)
porchctl rpkg push "$BLUEPRINT" "$HERE/work/blueprints/network-function/" --namespace=porch-demo
porchctl rpkg propose "$BLUEPRINT" --namespace=porch-demo
porchctl rpkg approve "$BLUEPRINT" --namespace=porch-demo
