#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../_env"
. "$ROOT/library/_trap"
. "$HERE/_env"

"$ROOT/platforms/kind/use" management

rm --force --recursive "$HERE/work/temporary/"

# Pull the blueprint and mutate it
BLUEPRINT=$("$ROOT/workloads/porch/package-revision-name" porch-demo "$GIT_BLUEPRINTS_REPO" network-function)
porchctl rpkg pull "$BLUEPRINT" "$HERE/work/temporary/" --namespace=porch-demo
kpt fn eval --image=gcr.io/kpt-fn/set-namespace:v0.4.1 "$HERE/work/temporary/" -- namespace=network-function-a

# Create the deployment package
DEPLOYMENT=$(porchctl rpkg init network-function-a --workspace=v1 --repository="$GIT_DEPLOYMENT_REPO" --namespace=porch-demo | cut --delimiter=' ' --fields=1)
porchctl rpkg pull "$DEPLOYMENT" "$HERE/work/temporary/" --namespace=porch-demo
porchctl rpkg push "$DEPLOYMENT" "$HERE/work/temporary/" --namespace=porch-demo
porchctl rpkg propose "$DEPLOYMENT" --namespace=porch-demo
porchctl rpkg approve "$DEPLOYMENT" --namespace=porch-demo

"$ROOT/platforms/kind/use" edge1

kubectl apply -f "$HERE/work/root-sync.yaml"
