apiVersion: config.porch.kpt.dev/v1alpha2
kind: PackageVariantSet

metadata:
  name: network-function
  namespace: porch-demo

spec:
  upstream:
    repo: $GIT_BLUEPRINTS_REPO
    package: network-function
    revision: v1
  targets:
    - repositories:
        - name: $GIT_DEPLOYMENT_REPO
          packageNames:
            - network-function-b
